version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODE=dev
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8080:8080'
