[tool.poetry]
name = "chainlit-langgraph"
version = "0.1.0"
description = ""
authors = ["Bruce Chou <brucechou1983@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
chainlit = "^1.0.504"
langchain = "^0.1.16"
langchain-openai = "^0.1.3"
langchain-anthropic = "^0.1.11"
langchain-google-genai = "^1.0.2"
langchain-experimental = "^0.0.57"
langgraph = "^0.0.38"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
